# Generated by Django 4.0 on 2021-12-27 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='StoreProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('img', models.ImageField(upload_to='StoreProducts/%y/%m/%d')),
                ('price', models.FloatField()),
                ('discount_price', models.FloatField(blank=True, null=True)),
                ('label', models.CharField(choices=[('sale', 'sale'), ('new', 'new')], max_length=20)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description_short', models.CharField(max_length=200)),
                ('description_long', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('available_count', models.IntegerField(default=1)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce_product.categoryproducts')),
            ],
        ),
    ]
