# Generated by Django 4.0 on 2021-12-27 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_product', '0002_alter_storeproducts_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeproducts',
            name='discount_price',
            field=models.FloatField(default=0),
        ),
    ]
