# Generated by Django 4.0 on 2021-12-28 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_product', '0003_alter_storeproducts_discount_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='SizeAndColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_name', models.CharField(max_length=3)),
                ('color_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='storeproducts',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scategory', to='ecommerce_product.categoryproducts'),
        ),
        migrations.AddField(
            model_name='storeproducts',
            name='size_color',
            field=models.ManyToManyField(to='ecommerce_product.SizeAndColor'),
        ),
    ]
