# Generated by Django 4.0 on 2021-12-28 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_product', '0004_sizeandcolor_alter_storeproducts_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SizeProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_name', models.CharField(max_length=3)),
            ],
        ),
        migrations.DeleteModel(
            name='SizeAndColor',
        ),
        migrations.AlterField(
            model_name='storeproducts',
            name='size_color',
            field=models.ManyToManyField(to='ecommerce_product.SizeProducts'),
        ),
    ]
