# Generated by Django 4.0 on 2021-12-28 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_product', '0005_sizeproducts_delete_sizeandcolor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sizeproducts',
            name='size_name',
            field=models.CharField(choices=[('size M ', 'M'), ('size L', 'L'), ('size XL', 'XL'), ('size 2XL', '2XL'), ('size 3XL', '3XL')], max_length=10),
        ),
    ]
