# Generated by Django 4.0 on 2021-12-28 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_product', '0006_alter_sizeproducts_size_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeproducts',
            name='size_color',
            field=models.ManyToManyField(related_name='ssize', to='ecommerce_product.SizeProducts'),
        ),
    ]
