# Generated by Django 4.0 on 2021-12-28 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_product', '0007_alter_storeproducts_size_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeproducts',
            name='size_color',
            field=models.ManyToManyField(related_name='mm', to='ecommerce_product.SizeProducts'),
        ),
    ]
