# Generated by Django 4.0 on 2021-12-28 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_product', '0009_alter_sizeproducts_size_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeproducts',
            name='category',
        ),
        migrations.AddField(
            model_name='storeproducts',
            name='category',
            field=models.ManyToManyField(related_name='scategory', to='ecommerce_product.CategoryProducts'),
        ),
    ]
