# Generated by Django 4.0 on 2021-12-29 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_product', '0011_remove_storeproducts_category_storeproducts_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeproducts',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scategory', to='ecommerce_product.categoryproducts'),
        ),
    ]
