# Generated by Django 4.0 on 2021-12-30 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_product', '0013_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryproducts',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='category'),
        ),
    ]
