# Generated by Django 4.0 on 2022-01-01 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='message',
            field=models.TextField(null=True),
        ),
    ]
